export const environment = {
  production: true,
  authToken: 'SAFSD;FSALDK;ALKS;DF;AKSDFASDFS0-DF9S-0D9F-A0S9-D09F-ASD-0F9SA-',
  AUTH_TOKEN:'SAFSD;FSALDK;ALKS;DF;AKSDFASDFS0-DF9S-0D9F-A0S9-D09F-ASD-0F9SA-',
  OPENAI_API_KEY: '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'
};
